namespace Aprs.Services;

public sealed record IGateConfiguration(
    bool IGateEnabled,
    bool RfToAprsIsGatingEnabled,
    bool AprsIsTransmitEnabled,
    bool AprsIsTransmitRequired,
    IReadOnlyList<string> AllowedRfSourcePorts,
    string? AprsIsDestinationConnectionProfile,
    bool DuplicateSuppressionEnabled,
    TimeSpan DuplicateDetectionWindow,
    int MaximumGateRatePerMinute,
    int MaximumGateRatePerStationPerMinute,
    bool RequireValidCallsign,
    bool RequireValidPacket,
    bool GatePositionPackets,
    bool GateWeatherPackets,
    bool GateObjectItemPackets,
    bool GateMessages,
    bool GateThirdPartyPackets,
    bool GateTelemetry,
    IReadOnlyList<string> BlockedPathPatterns,
    IReadOnlyList<string> AllowedPathPatterns,
    bool RequireExplicitConfirmationBeforeEnabling,
    DateTimeOffset CreatedTimestampUtc,
    DateTimeOffset UpdatedTimestampUtc)
{
    public static IGateConfiguration Default { get; } = new(
        IGateEnabled: false,
        RfToAprsIsGatingEnabled: false,
        AprsIsTransmitEnabled: false,
        AprsIsTransmitRequired: true,
        AllowedRfSourcePorts: [],
        AprsIsDestinationConnectionProfile: null,
        DuplicateSuppressionEnabled: true,
        DuplicateDetectionWindow: TimeSpan.FromMinutes(30),
        MaximumGateRatePerMinute: 10,
        MaximumGateRatePerStationPerMinute: 3,
        RequireValidCallsign: true,
        RequireValidPacket: true,
        GatePositionPackets: true,
        GateWeatherPackets: true,
        GateObjectItemPackets: true,
        GateMessages: true,
        GateThirdPartyPackets: false,
        GateTelemetry: false,
        BlockedPathPatterns: ["TCPIP*", "TCPXX*", "q*"],
        AllowedPathPatterns: [],
        RequireExplicitConfirmationBeforeEnabling: true,
        CreatedTimestampUtc: DateTimeOffset.MinValue,
        UpdatedTimestampUtc: DateTimeOffset.MinValue);
}
